---
swagger: "2.0"
info:
  version: 0.0.1-rev6
  title: SCP Budgets API
  x-ibm-name: scp-budgets-api
  description: ""
basePath: /clients
schemes:
- https
x-ibm-configuration:
  enforced: true
  phase: realized
  testable: true
  externalDocs: []
  attachments: []
tags: []
definitions:
  Budget:
    properties:
      CycleStartDay:
        type: integer
        format: int32
        description: The day the budget cycle starts on
      ShadowData:
        type: boolean
        description: Indicates if this budget was automatically created
      IncomeBudgetItems:
        type: array
        $ref: '#/definitions/BudgetLineItem'
      ExpenseBudgetItems:
        type: array
        $ref: '#/definitions/BudgetLineItem'
  BudgetLineItem:
    properties:
      CategoryId:
        type: integer
        format: int32
        description: The id of the category
      Target:
        type: number
        format: double
        description: The target spend amount for this category
      Actual:
        type: number
        format: double
        description: The actual spend amount for this category
  CategoryGroup:
    properties:
      CategoryGroupId:
        type: string
        description: The identifier for the category group
      CategoryGroupDescription:
        type: string
        description: The name of the category group
      CategoryGroupIconClass:
        type: string
        description: A class name corresponding to the category group icon
      CategoryGroupColour:
        type: string
        description: A colour corresponding to the category group
      GroupCategories:
        type: array
        items:
          type: integer
          format: int32
  CategoryDefault:
    properties:
      CategoryId:
        type: integer
        format: int32
        description: The category Id
      CategoryName:
        type: string
        description: The name for this category
      OriginalName:
        type: string
        description: The name for this category
      CategoryImage:
        type: string
        description: The image name for this category
      CategoryColour:
        type: string
        description: The colour for this category
  BudgetGroup:
    properties:
      BudgetGroupId:
        type: integer
        format: int32
        description: The id of the category
      BudgetGroupDescription:
        type: string
        description: The budget group description
      BudgetGroupIconClass:
        type: string
        description: The icon name for this budgetgroup
      BudgetCategories:
        type: array
        items:
          type: integer
          format: int32
          description: The category type Id
  Category:
    properties:
      CategoryId:
        type: integer
        format: int32
        description: The category Id
      CategoryTypeId:
        type: integer
        format: int32
        description: The category type Id
      Name:
        type: string
        description: The name for this category
      CategoryColour:
        type: string
        description: The colour for this category
      CategoryImage:
        type: string
        description: The image name for this category
      Spend:
        type: number
        format: double
        description: The actual spend amount for this category
      User:
        type: boolean
        description: Indicates if this budget was automatically created
paths:
  /budgets:
    get:
      description: Gets the 'Budget' object for the user
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      - name: budgetdate
        type: string
        required: false
        in: query
        description: ""
      responses:
        200:
          description: Successful response
          schema:
            title: Budget
            $ref: '#/definitions/Budget'
          examples:
            application/json:
              CycleStartDay: 1
              ShadowData: false
              IncomeBudgetItems:
              - CategoryId: 29
                Target: 818.230000
              ExpenseBudgetItems:
              - CategoryId: 24
                Target: 153.330000
              - CategoryId: 45
                Target: 11.670000
              - CategoryId: 14
                Target: 457.550000
              - CategoryId: 15
                Target: 141.670000
              - CategoryId: 11
                Target: 88.330000
              - CategoryId: 38
                Target: 3566.670000
              - CategoryId: 3
                Target: 333.330000
              - CategoryId: 2
                Target: 383.330000
              - CategoryId: 100
                Target: 0
                Actual: 0
              - CategoryId: 25
                Target: 0
                Actual: 0
              - CategoryId: 102
                Target: 0
                Actual: 0
              - CategoryId: 33
                Target: 0
                Actual: 0
              - CategoryId: 4
                Target: 0
                Actual: 0
              - CategoryId: 5
                Target: 0
                Actual: 0
              - CategoryId: 108
                Target: 0
                Actual: 0
              - CategoryId: 6
                Target: 0
                Actual: 0
              - CategoryId: 43
                Target: 0
                Actual: 0
              - CategoryId: 7
                Target: 0
                Actual: 0
              - CategoryId: 8
                Target: 0
                Actual: 0
              - CategoryId: 44
                Target: 0
                Actual: 0
              - CategoryId: 9
                Target: 0
                Actual: 0
              - CategoryId: 10
                Target: 0
                Actual: 0
              - CategoryId: 34
                Target: 0
                Actual: 0
              - CategoryId: 13
                Target: 0
                Actual: 0
              - CategoryId: 12
                Target: 0
                Actual: 0
              - CategoryId: 17
                Target: 0
                Actual: 0
              - CategoryId: 18
                Target: 0
                Actual: 0
              - CategoryId: 110
                Target: 0
                Actual: 0
              - CategoryId: 16
                Target: 0
                Actual: 0
              - CategoryId: 35
                Target: 0
                Actual: 0
              - CategoryId: 19
                Target: 0
                Actual: 0
              - CategoryId: 20
                Target: 0
                Actual: 0
              - CategoryId: 42
                Target: 0
                Actual: 0
              - CategoryId: 104
                Target: 0
                Actual: 0
              - CategoryId: 106
                Target: 0
                Actual: 0
              - CategoryId: 21
                Target: 0
                Actual: 0
              - CategoryId: 22
                Target: 0
                Actual: 0
              - CategoryId: 37
                Target: 0
                Actual: 0
              - CategoryId: 23
                Target: 0
                Actual: 0
              - CategoryId: 39
                Target: 0
                Actual: 0
              - CategoryId: 112
                Target: 0
                Actual: 0
      security:
      - API Key (Query): []
      - API Key: []
      summary: ""
    post:
      description: ""
      tags: []
      parameters:
      - description: ""
        name: Authorization
        required: true
        type: string
        in: header
      - schema:
          example: |-
            {
               "CycleStartDay": 1,
               "ShadowData": false,
               "IncomeBudgetItems": [
                  {
                     "CategoryId": 29,
                     "Target": 818.23,
                     "Actual": 818.23
                  }
               ],
               "ExpenseBudgetItems": [
                  {
                     "CategoryId": 24,
                     "Target": 153.33,
                     "Actual": 150
                  },
                  {
                     "CategoryId": 45,
                     "Target": 11.67,
                     "Actual": 12.01
                  },
                  {
                     "CategoryId": 14,
                     "Target": 457.55
                  },
                  {
                     "CategoryId": 15,
                     "Target": 141.67
                  },
                  {
                     "CategoryId": 11,
                     "Target": 88.33
                  }
               ]
            }
          $ref: '#/definitions/Budget'
        description: Budget object that needs to be added or updated for the specific
          user
        name: body
        required: true
        in: body
      responses:
        201:
          description: Created
        405:
          description: Invalid input
      security:
      - API Key (Query): []
      - API Key: []
      summary: Adds or updates a budget for a user
  /budgets/categorygroups:
    get:
      description: Gets the 'CategoryGroup' objects
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfCategoryGroups
            type: array
            items:
              title: CategoryGroups
              type: array
              items:
                $ref: '#/definitions/CategoryGroup'
          examples: []
      security:
      - API Key (Query): []
      - API Key: []
      summary: ""
    post:
      description: ""
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      - schema:
          title: ArrayOfCategoryGroups
          type: array
          items:
            title: CategoryGroups
            type: array
            items:
              $ref: '#/definitions/CategoryGroup'
        description: CategoryGroup array that needs to be updated
        name: body
        required: true
        in: body
      responses:
        200:
          description: OK
        405:
          description: Invalid input
      security:
      - API Key (Query): []
      - API Key: []
      summary: Adds or updates the budget groups
  /budgets/categorydefaults:
    get:
      description: Gets the 'CategoryDefault' objects
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfCategoryDefaults
            type: array
            items:
              title: CategoryDefaults
              type: array
              items:
                $ref: '#/definitions/CategoryDefault'
          examples: []
      security:
      - API Key (Query): []
      - API Key: []
      summary: ""
    post:
      description: ""
      tags: []
      parameters:
      - description: ""
        name: Authorization
        required: true
        type: string
        in: header
      - schema:
          title: CategoryDefaults
          type: array
          items:
            $ref: '#/definitions/CategoryDefault'
          example: |-
            [
               {
                  "CategoryId": 100,
                  "CategoryName": "Advertising",
                  "OriginalName": "Advertising",
                  "CategoryImage": "glyphicon-category_advertising",
                  "CategoryColour": "colorType-background-category_advertising"
               }
            ]
        description: CategoryDefault array that needs to be updated
        name: body
        required: true
        in: body
      responses:
        200:
          description: OK
        405:
          description: Invalid input
      security:
      - API Key (Query): []
      - API Key: []
      summary: Adds or updates the client category defaults
  /budgets/budgetgroups:
    get:
      description: Gets the 'CategoryGroup' objects
      tags: []
      parameters:
      - description: ""
        name: Authorization
        required: true
        type: string
        in: header
      responses:
        200:
          schema:
            title: Category
            type: array
            items:
              $ref: '#/definitions/BudgetGroup'
          description: ""
      security:
      - API Key (Query): []
      - API Key: []
      summary: ""
  /budgets/categories:
    get:
      description: Gets the Categories objects
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          schema:
            title: Category
            type: array
            items:
              $ref: '#/definitions/Category'
          description: ""
      security:
      - API Key (Query): []
      - API Key: []
      summary: ""
security:
- API Key (Query): []
- API Key: []
x-ibm-endpoints:
- endpointUrl: https://api-e.nedsecure.co.za/nedbankext
  description: Base Gateway API Endpoint
  type:
  - development
...
