---
swagger: "2.0"
info:
  version: 1.0.0
  title: Enquiries API
  x-ibm-name: enquiries-api
  description: ""
basePath: /transactions/v1
parameters:
  Authorization:
    name: Authorization
    type: string
    required: true
    in: header
    description: ""
consumes:
- application/json
produces:
- application/json
schemes:
- https
securityDefinitions:
  api-key:
    type: apiKey
    description: ""
    in: header
    name: X-IBM-Client-Id
security:
- api-key: []
paths:
  /transactionsenquiry:
    get:
      description: Retrieves transactions on enquiries (failed/successful)
      parameters:
      - description: This specifies the from account for which you want to retrieve
          transactions
        in: query
        name: fromacc
        type: string
        required: false
      - description: This specifies the from date of the enquiry
        in: query
        name: fromdate
        type: string
        format: date
        required: false
      - description: This specifies the to date of the enquiry
        in: query
        name: todate
        type: string
        format: date
        required: false
      - description: This specifies the service provider type (BLT, GDN, VDC, MTN
          etc...)
        in: query
        name: serviceprovider
        type: string
        required: false
      - description: This specifies the prepaid type/code (PAI (Prepaid Airtime);
          PBB (Prepaid Big Bonus Voucher); PBS (Prepaid Blackberry Service); PCB (all
          in one); PDA (Prepaid Data Bundle); PEL (Prepaid Electricity); PMC (MTN
          Chat); PMI (MTN internetExplore); PML (MTNSmartphonelite); PNM (SocailNetworking);
          PMP (smartphoneplus); PLO (Lotto); PSM (prepaid sms bundle); PMS (Money
          Send); PVC (Prepaid SMS Bundle); PWA (Prepaid Without Airtime); PDB (power
          DATA bundle); PDW (WIFI Data bundle); PVB (Power voice bundle); ALL; U0
          (Undefined))
        in: query
        name: prepaidtype
        type: string
        required: false
      - description: This specifies the destination number (cell, telephone, electricity
          meter)
        in: query
        name: destinationnumber
        type: string
        required: false
      - description: This specifies the addendum number
        in: query
        name: addendumnr
        type: string
        required: false
      - description: This specifies the from cheque number
        in: query
        name: fromchequenr
        type: string
        required: false
      - description: This specifies the to cheque number
        in: query
        name: tochequenr
        type: string
        required: false
      - description: This specifies the from amount for which you want to retrieve
          transactions
        in: query
        name: fromamount
        type: integer
        format: double
        required: false
      - description: This specifies the to amount for which you want to retrieve transactions
        in: query
        name: toamount
        type: integer
        format: double
      - description: This specifies the lotto game
        in: query
        name: lottogame
        type: string
      - description: This specifies the lotto game type
        in: query
        name: lottogametype
        type: string
        required: false
      - description: This specifies the money send type
        in: query
        name: monetsendtype
        type: integer
        format: double
        required: false
      - description: This specifies the transaction type for which you want to retrieve
          transactions  (Payments; Transfers; Prapaids; Lotto; MoneyTransfer)
        in: query
        name: transactiontype
        type: string
        required: true
      - description: This specifies if the client wants to "search for transactions"
          or "view failed transactions (failedtransactions = true". If failedtransactions
          = 'false' then do search for transactions.
        in: query
        name: failedtransactions
        type: boolean
        required: true
      - description: This specifies the page to view
        in: query
        name: page
        type: string
        required: false
      - description: This specifies the amount of records per page for viewing
        in: query
        name: pagesize
        type: string
        required: false
      responses:
        200:
          description: Request successful
          schema:
            $ref: '#/definitions/TransactionEnquiryResponse'
        204:
          description: No Content
        207:
          description: Partial success
          schema:
            $ref: '#/definitions/TransactionEnquiryResponse'
        default:
          description: Returns an error that has not been specified in the implementation.
            Additional information may be contained in the Metadata object
          schema:
            $ref: '#/definitions/TransactionEnquiryResponse'
    parameters:
    - $ref: '#/parameters/Authorization'
definitions:
  TransactionEnquiryResponse:
    properties:
      data:
        $ref: '#/definitions/TransactionEnquiries'
      metadata:
        $ref: '#/definitions/Metadata'
  TransactionEnquiries:
    properties:
      Prepaids:
        description: list of enquiry transactions
        type: array
        items:
          $ref: '#/definitions/TransactionEnquiry'
  TransactionEnquiry:
    properties:
      transactionDate:
        description: (used by - Payments, Transfers, Prepaids, Lotto, MoneySend) -
          mapped to ReturnDate (for failed transactions) or ValueDate (for other trnasactions)
        type: string
        format: Date
      fromAccount:
        description: (used by - Payments, Transfers, Prepaids, Lotto, MoneySend)
        type: string
      toAccount:
        description: (used by - Payments, Transfers)
        type: string
      branchCode:
        description: (used by - Payments)
        type: string
      destinationNumber:
        description: (used by - Prepaids, MoneySend)
        type: string
      serviceProvider:
        description: (used by - Prepaids) - i.e. If 'VDC' return 'Vocacom' here (full
          name must be returned as front-end will not have access to the SQL/Mongo
          DB for translation)
        type: string
      prepaidType:
        description: (used by - Prepaids) - ProductCode converted to full name must
          be returned i.e. If 'PDA' return 'Prepaid Data Bundle' here
        type: string
      beneficiaryName:
        description: (used by - Payments)
        type: string
      myDescription:
        description: (used by - Lotto)
        type: string
      beneficiaryDescription:
        description: (used by - Transfers)
        type: string
      lottoGameDetail:
        description: (used by - Lotto)
        type: string
      purchaseRefNr:
        description: (used by - Prepaids, Lotto, MnoeySend) - ValueDate/NEDBANK/ExecEngineRef
        type: string
      amount:
        description: (used by - Payments, Transfers, Prepaids, Lotto, MoneySend)
        type: integer
        format: double
      statusReason:
        description: (used by - Payments, Transfers, Prepaids, Lotto, MoneySend)
        type: string
      notificationDetails:
        $ref: '#/definitions/NotificationDetails'
  NotificationDetails:
    properties:
      Prepaids:
        description: (used by - Payments, Prepaids, Lotto, MoneySend.mpesa) - only
          used for transactions that was successful (not for failed transactions)
        type: array
        items:
          $ref: '#/definitions/NotificationDetail'
  NotificationDetail:
    properties:
      NotificationType:
        description: NONE; SMS; FAX; EMAIL, SecureInbox
        type: string
        enum:
        - NONE
        - SMS
        - FAX
        - EMAIL
        - SecureInbox
      NotificationAddress:
        description: mobile number; email address etc
        type: string
      NotificationDefaultInd:
        description: only used for adding/maintianing an electricity meter
        type: boolean
  Metadata:
    properties:
      Page:
        description: current page number/location
        type: integer
        format: int32
      PageSize:
        description: the amount of records to be retrieved per page (is editable)
        type: integer
        format: int32
      PageLimit:
        description: the total amount of available records
        type: integer
        format: int32
      ResultData:
        description: returns result code and description
        type: array
        items:
          $ref: '#/definitions/ResultData'
  ResultData:
    properties:
      BatchID:
        description: Used for now and futuredated
        type: string
      TransactionID:
        description: Used here for the 'match back' to front-end in order to display
          status per transaction (now, futuredated, & recurring)
        type: string
      RecInstrID:
        description: Used for recurring instruction
        type: string
      ResultDetail:
        description: There are instances where ONE transaction can include multiple
          API-to-BackEnd calls (i.e. payment + notification + save as beneficiary
          + make favourite = 4-5 calls).
        type: array
        items:
          $ref: '#/definitions/ResultDetail'
      ExecEngineRef:
        description: Executing engine (host) reference number
        type: string
  ResultDetail:
    properties:
      OperationReference:
        description: Indicates which operation this result is for on the current transaction
          i.e. transfer successfull but adding favourite failed. Values can include
          the following 'Transaction', 'Notification - NotificationAddress (082...)',
          'Favourite', 'BeneficiarySaved'. The 'Transaction' type are for any transaction
          i.e. payment, transfer, get, delete etc.
        type: string
      Result:
        description: Can pass the error code here.
        type: string
      Status:
        description: Can pass the error description here.
        type: string
      Reason:
        description: Error description
        type: string
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
x-ibm-endpoints:
- endpointUrl: https://api-e.nedsecure.co.za/nedbankext
  description: Base Gateway API Endpoint
  type:
  - development
...
