---
swagger: "2.0"
info:
  version: 0.0.1-rev5
  title: SCP Expenses API
  x-ibm-name: scp-expenses-api
  description: ""
basePath: /clients
schemes:
- https
x-ibm-configuration:
  enforced: true
  phase: realized
  testable: true
  externalDocs: []
  attachments: []
tags: []
definitions:
  MonthlySpend:
    properties:
      DateStart:
        type: string
        description: The name of the category
      DateEnd:
        type: string
        description: The id of the category
      CategorySpendArray:
        type: array
        items:
          $ref: '#/definitions/CategorySpend'
  CategorySpend:
    properties:
      CategoryName:
        type: string
        description: The name of the category
      CategoryId:
        type: integer
        format: int32
        description: The id of the category
      Spend:
        type: number
        format: double
        description: The spend amount for this category
securityDefinitions:
  API Key:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    description: ""
  API Key (Query):
    type: apiKey
    name: client_id
    in: query
    description: ""
paths:
  /expenses/monthly:
    get:
      description: Gets 'MonthlySpend' objects containing categorised transactions
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfMonthlySpend
            type: array
            items:
              title: MonthlySpends
              type: array
              items:
                $ref: '#/definitions/MonthlySpend'
      summary: ""
  /expenses/categoryspend:
    get:
      description: Gets 'CategorySpend' objects containing categorised transactions
      tags: []
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfCategorySpend
            type: array
            items:
              title: CategorySpends
              type: array
              items:
                $ref: '#/definitions/CategorySpend'
      summary: ""
security:
- API Key: []
- API Key (Query): []
x-ibm-endpoints:
- endpointUrl: https://api-e.nedsecure.co.za/nedbankext
  description: Base Gateway API Endpoint
  type:
  - development
...
