swagger: '2.0'
info:
  title: Nedbank Api Combined Contracts
  version: 1.0.0
apis:
  - url: 'contracts/NedbankID.yaml'
    paths:
      base: '/api/idservice'
  - url: 'contracts/Beneficiary API.yaml'
    paths:
      base: '/api/beneficiaryservice'
  - url: 'contracts/ContactCards API.yaml'
    paths:
      base: '/api/contactcardsservice'
  - url: 'contracts/Enquiries API.yaml'
    paths:
      base: '/api/enquiriesservice'
  - url: 'contracts/FicaMe API.yaml'
    paths:
      base: '/api/ficameservice'
  - url: 'contracts/Information Notices.yaml'
    paths:
      base: '/api/informationnoticesservice'
  - url: 'contracts/LOTTO API.yaml'
    paths:
      base: '/api/lottoservice'
  - url: 'contracts/Payments API.yaml'
    paths:
      base: '/api/paymentsservice'
  - url: 'contracts/Preference API.yaml'
    paths:
      base: '/api/preferenceservice'
  - url: 'contracts/Prepaids API.yaml'
    paths:
      base: '/api/prepaidservice'
  - url: 'contracts/ReferenceData API.yaml'
    paths:
      base: '/api/referencedataservice'
  - url: 'contracts/SCP Accounts API.yaml'
    paths:
      base: '/api/accountsservice'
  - url: 'contracts/SCP Budgets API.yaml'
    paths:
      base: '/api/budgetservice'
  - url: 'contracts/SCP Clients API.yaml'
    paths:
      base: '/api/clientsservice'
  - url: 'contracts/SCP Expenses API.yaml'
    paths:
      base: '/api/expensesservice'
  - url: 'contracts/SCP Goals API.yaml'
    paths:
      base: '/api/goalsservice'
  - url: 'contracts/SCP NGI API.yaml'
    paths:
      base: '/api/ngiservice'
  - url: 'contracts/Terms & Conditions API.yaml'
    paths:
      base: '/api/termsandconditionsservice'
  - url: 'contracts/Transfers API.yaml'
    paths:
      base: '/api/transfersservice'
