swagger: "2.0"
info:
  version: "0.0.1"
  title: FicaMyself API
# during dev, should point to your local machine
paths:
  /id-verification/v2/parties/{partyId}/IDOCRExtractions:
    x-swagger-router-controller: customers
    post:
      operationId: idDocument
      description: Get customer details from identity document image (passport, ID Card or ID Book)
      parameters:
        - name: partyId
          in: path
          required: true
          type: string
        - name: request
          in: body
          required: true
          schema:
            type: object
            properties:
              frontImage:
                type: string
              rearImage:
                type: string
              idType:
                type: string
      responses:
        "200":
          description: success
          schema:
            type: object
            properties:
              firstname:
                type: string
              middlename:
                type: string
              lastname:
                type: string
              idNumber:
                type: string
              timestamp:
                type: string

  
  /address-verification/v2/parties/address-document:
    post:
      description: Mines for the customer address from the vendor
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - name: request
          in: body
          required: true
          schema:
            type: object
            properties:
              partyId:
                type: string
              document:
                type: string
              documentType:
                type: string
      responses: 
        "200":
          description: success
          schema: 
            type: object
            properties: 
              responseMessage:
                type: string
    
  /address-verification/v2/parties/match-address:
    post:
      operationId: address
      description: OCRs the address document and returns the address
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - name: request
          in: body
          required: true
          schema:
            type: object
            properties:
              address:
                type: string
              partyId:
                type: string
              surname:
                type: string
              idNumber:
                type: string
              passport:
                type: string
      responses:
        "200":
          description: success
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  confidenceLevel:
                    type: string
                  addressConfirmed:
                    type: string
                  
                    
            
            
  /id-verification/v2/parties/{partyId}/facialRecognitionProfiles:
    post:
      description: Compares an image of a face with an ID document or passport
      consumes: [application/json]
      produces: [application/json]
      parameters:
        - name: partyId
          in: path
          required: true
          type: string
        - name: request
          in: body
          required: true
          schema: 
            type: object
            properties:
              facialImage:
                type: string
      responses:
        "200":
          description: Success
          schema:
            type: "object"
            properties: 
              isMatch: 
                type: boolean
              error:
                type: string
  /swagger:
    x-swagger-pipe: swagger_raw


