---
swagger: "2.0"
info:
  version: 1.0.0
  title: Nedbank APR
  description: Nedbank API services
basePath: /api/services/v1
host: localhost:10010
consumes:
- application/json
produces:
- application/json
schemes:
- http
- https
paths:
  /test:
    get:
      description: "This endpoint returns all todos available in the database"
      operationId: "Test"
      x-swagger-router-controller: "Test"
      parameters: []
      responses:
        200:
          description: "An array of todos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
definitions:
...
