---
swagger: "2.0"
info:
  title: Information Notices
  description: ""
  version: 1.0.1
  x-ibm-name: information-notices
# schemes:
# - https
# basePath: /interactionenablers/v1
# consumes:
# - application/json
# - application/xml
# produces:
# - application/json
# - application/xml
paths:
  /infonotices/channels/{channelid}/brands/{brandid}/types/{typeof}/users/{userid}:
    put:
      operationId: acceptInformationNotice
      x-swagger-router-controller: information_notices
      summary: Accept Information Notice
      parameters:
      - $ref: '#/parameters/channelid'
      - $ref: '#/parameters/brandid'
      - $ref: '#/parameters/typeof'
      - $ref: '#/parameters/userid'
      - name: AcceptanceDetails
        in: body
        required: true
        schema:
          $ref: '#/definitions/AcceptanceDetails'
      - name: Authorization
        type: string
        required: true
        in: header
      tags:
      - Accept Information Notice
      responses:
        200:
          description: Request has been successfully executed and the information
            notice has been accepted. The ErrorDescription.ErrorCode must be R00
          schema:
            $ref: '#/definitions/ErrorDescription'
        400:
          description: The request could not be understood by the server due to malformed
            syntax. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        401:
          description: The request requires user authentication. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        404:
          description: The server has not found anything matching the Request-URI.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        405:
          description: The method specified in the Request-Line is not allowed for
            the resource identified by the Request-URI. Additional information may
            be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        415:
          description: The server is refusing to service the request because the entity
            of the request is in a format not supported by the requested resource
            for the requested method. Additional information may be contained in the
            Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        500:
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request. This usually indicates that there where
            errors executing calls in the MDM system. Additional information may be
            contained in the MDM Object Error object
          schema:
            $ref: '#/definitions/ErrorDescription'
        501:
          description: The server does not support the functionality required to fulfil
            the request. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        503:
          description: The server is currently unable to handle the request due to
            a temporary overloading or maintenance of the server. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        default:
          description: Returns an error that has not been specified in the implementation.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
    get:
      operationId: getInformationNotice
      x-swagger-router-controller: information_notices
      summary: Get Information Notice
      parameters:
      - $ref: '#/parameters/channelid'
      - $ref: '#/parameters/brandid'
      - $ref: '#/parameters/typeof'
      - $ref: '#/parameters/userid'
      - name: versionnumber
        in: query
        description: The version number of the notice
        required: true
        type: string
      - name: Authorization
        type: string
        required: true
        in: header
      tags:
      - Get Information Notice
      responses:
        200:
          description: Request has been successfully executed and a list of a Person's
            details according to the specific business context is returned
          schema:
            $ref: '#/definitions/NoticeDetails'
        400:
          description: The request could not be understood by the server due to malformed
            syntax. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        401:
          description: The request requires user authentication. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        404:
          description: The server has not found anything matching the Request-URI.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        405:
          description: The method specified in the Request-Line is not allowed for
            the resource identified by the Request-URI. Additional information may
            be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        415:
          description: The server is refusing to service the request because the entity
            of the request is in a format not supported by the requested resource
            for the requested method. Additional information may be contained in the
            Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        500:
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request. This usually indicates that there where
            errors executing calls in the MDM system. Additional information may be
            contained in the MDM Object Error object
          schema:
            $ref: '#/definitions/ErrorDescription'
        501:
          description: The server does not support the functionality required to fulfil
            the request. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        503:
          description: The server is currently unable to handle the request due to
            a temporary overloading or maintenance of the server. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        default:
          description: Returns an error that has not been specified in the implementation.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
  /infonotices/channels/{channelid}/brands/{brandid}/types/{typeof}/users/{userid}/summary:
    get:
      operationId: checkForNotice
      x-swagger-router-controller: information_notices
      summary: Retrieve A List of Notices for a Specific User
      parameters:
      - $ref: '#/parameters/channelid'
      - $ref: '#/parameters/brandid'
      - $ref: '#/parameters/typeof'
      - $ref: '#/parameters/userid'
      - name: Authorization
        type: string
        required: true
        in: header
      tags:
      - Retrieve A List of Notices for a Specific User
      responses:
        200:
          description: Request has been successfully executed and a list of a Person's
            details according to the specific business context is returned
          schema:
            $ref: '#/definitions/NoticesSummaryList'
        400:
          description: The request could not be understood by the server due to malformed
            syntax. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        401:
          description: The request requires user authentication. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        404:
          description: The server has not found anything matching the Request-URI.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        405:
          description: The method specified in the Request-Line is not allowed for
            the resource identified by the Request-URI. Additional information may
            be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        415:
          description: The server is refusing to service the request because the entity
            of the request is in a format not supported by the requested resource
            for the requested method. Additional information may be contained in the
            Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        500:
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request. This usually indicates that there where
            errors executing calls in the MDM system. Additional information may be
            contained in the MDM Object Error object
          schema:
            $ref: '#/definitions/ErrorDescription'
        501:
          description: The server does not support the functionality required to fulfil
            the request. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        503:
          description: The server is currently unable to handle the request due to
            a temporary overloading or maintenance of the server. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        default:
          description: Returns an error that has not been specified in the implementation.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
  /infonotices/channels/{channelid}/brands/{brandid}/types/{typeof}:
    get:
      operationId: getLatestNoticeVersion
      x-swagger-router-controller: information_notices
      summary: Retrieve the Latest Version of a Notice
      parameters:
      - $ref: '#/parameters/channelid'
      - $ref: '#/parameters/brandid'
      - $ref: '#/parameters/typeof'
      - name: Authorization
        type: string
        required: true
        in: header
      tags:
      - Retrieve the Latest Version of a Notice
      responses:
        200:
          description: Request has been successfully executed and a list of a Person's
            details according to the specific business context is returned
          schema:
            $ref: '#/definitions/NoticeDetails'
        400:
          description: The request could not be understood by the server due to malformed
            syntax. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        401:
          description: The request requires user authentication. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        404:
          description: The server has not found anything matching the Request-URI.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        405:
          description: The method specified in the Request-Line is not allowed for
            the resource identified by the Request-URI. Additional information may
            be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        415:
          description: The server is refusing to service the request because the entity
            of the request is in a format not supported by the requested resource
            for the requested method. Additional information may be contained in the
            Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        500:
          description: The server encountered an unexpected condition which prevented
            it from fulfilling the request. This usually indicates that there where
            errors executing calls in the MDM system. Additional information may be
            contained in the MDM Object Error object
          schema:
            $ref: '#/definitions/ErrorDescription'
        501:
          description: The server does not support the functionality required to fulfil
            the request. Additional information may be contained in the Error Description
            object
          schema:
            $ref: '#/definitions/ErrorDescription'
        503:
          description: The server is currently unable to handle the request due to
            a temporary overloading or maintenance of the server. Additional information
            may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
        default:
          description: Returns an error that has not been specified in the implementation.
            Additional information may be contained in the Error Description object
          schema:
            $ref: '#/definitions/ErrorDescription'
parameters:
  channelid:
    name: channelid
    in: path
    description: Identifies on which channel the user is currently logged in
    required: true
    type: integer
    format: int64
  brandid:
    name: brandid
    in: path
    description: Indicates the Brand of the client
    required: true
    type: string
  typeof:
    name: typeof
    in: path
    description: Indicates the Type of Notice
    required: true
    type: string
    default: AAA
    enum:
    - AAA
    - AAB
    - AAC
    - AVS
    - ACC
    - AWA
    - BBB
    - CCC
    - DDD
    - DOC
    - DOF
    - EBP
    - EEE
    - ENT
    - EPM
    - ESC
    - ESH
    - EST
    - FAI
    - FFF
    - FTI
    - FTL
    - GGG
    - HHH
    - HLN
    - III
    - INF
    - IOD
    - IPN
    - JJJ
    - KKK
    - LLL
    - LTO
    - MMM
    - MNS
    - NBB
    - NID
    - NNN
    - NTC
    - OOO
    - PFM
    - PLA
    - PLB
    - PPE
    - PPP
    - PTI
    - QQQ
    - RRR
    - SAP
    - SEC
    - SSS
    - TTT
    - UUU
    - VVV
    - WWW
    - XXX
    - XYZ
    - YYY
    - ZZZ
  userid:
    name: userid
    in: path
    description: A unique identifier that identifies the user
    required: true
    type: string
definitions:
  AcceptanceDetails:
    type: object
    properties:
      Version:
        $ref: '#/definitions/VersionDetails'
      AcceptedDateTime:
        type: string
        format: date-time
        description: The date and time on which the notice was accepted
  PresentationList:
    type: object
    properties:
      PresentationTemplateType:
        type: string
        description: Indicates the type of presentation template
        default: DH
        enum:
        - DH
        - PH
      NoticePresentationTemplate:
        type: string
        description: A template that is used to display the notice content. Compressed
          huffman Base64 encoded
  NoticeDetails:
    type: object
    properties:
      Type:
        $ref: '#/definitions/NoticeTypeEnum'
      Content:
        type: string
        description: The content of the information notice. Compressed huffman Base64
          encoded data
      PresentationList:
        type: array
        items:
          $ref: '#/definitions/PresentationList'
      Version:
        $ref: '#/definitions/VersionDetails'
      DocumentId:
        type: string
        description: Uniquely identifies the document or image
      DocumentExt:
        type: string
        description: The extention value of an attached document
      DocumentName:
        type: string
        description: The name of the document attached to a notice
      DocumentCategoryCode:
        type: integer
        format: int64
        description: The category code for the attached document
      DocumentTypeCode:
        type: integer
        format: int64
        description: The product code for the attached document
  NoticeTypeEnum:
    description: Indicates the Type of Notice, e.g. AVS = Account Verification Service
      for NBB and CAP Self Enrolment, ACC = Accounting, AWA = Airtime without Airtime
      etc
    type: string
    default: AAA
    enum:
    - AAA
    - AAB
    - AAC
    - AVS
    - ACC
    - AWA
    - BBB
    - CCC
    - DDD
    - DOC
    - DOF
    - EBP
    - EEE
    - ENT
    - EPM
    - ESC
    - ESH
    - EST
    - FAI
    - FFF
    - FTI
    - FTL
    - GGG
    - HHH
    - HLN
    - III
    - INF
    - IOD
    - IPN
    - JJJ
    - KKK
    - LLL
    - LTO
    - MMM
    - MNS
    - NBB
    - NID
    - NNN
    - NTC
    - OOO
    - PFM
    - PLA
    - PLB
    - PPE
    - PPP
    - PTI
    - QQQ
    - RRR
    - SAP
    - SEC
    - SSS
    - TTT
    - UUU
    - VVV
    - WWW
    - XXX
    - XYZ
    - YYY
    - ZZZ
  NoticesSummaryList:
    type: array
    items:
      type: object
      properties:
        Type:
          $ref: '#/definitions/NoticeTypeEnum'
        Version:
          $ref: '#/definitions/VersionDetails'
  VersionDetails:
    type: object
    properties:
      VersionNumber:
        type: number
        format: float
        description: The version number of the notice
      VersionDate:
        type: string
        format: date-time
        description: The date of the version of the notice
  ErrorDescription:
    type: object
    properties:
      ErrorMessage:
        type: string
      ErrorCode:
        type: string
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
x-ibm-endpoints:
- endpointUrl: https://api-e.nedsecure.co.za/nedbankext
  description: Base Gateway API Endpoint
  type:
...
