---
swagger: "2.0"
info:
  version: 0.0.3
  title: SCP NGI API
  x-ibm-name: scp-ngi-api
  description: ""
paths:
  /investornumber:
    get:
      tags: []
      summary: ""
      description: Verifies that we can do investment servicing for this client and returns an investment number
      x-swagger-router-controller: scp_ngi
      operationId: investorNumber
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          description: OK
          schema:
            title: Investor Number
            type: string
        204:
          description: No Content
      deprecated: false
  /linkedsourceoffunds/{investornumber}:
    get:
      tags: []
      summary: ""
      description: Gets any linked sources of funds for the client
      x-swagger-router-controller: scp_ngi
      operationId: linkedSourceOfFunds
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      - name: investornumber
        type: string
        required: true
        in: path
      responses:
        200:
          description: OK
          schema:
            title: LinkedFundSources
            type: array
            items:
              $ref: '#/definitions/LinkedFundSource'
          examples:
            application/json:
            - LinkedFundSource:
                Identifier: 5224772
                Number: 50045199
                Type: Current Account
                Name: Mr DS COOPER
                InstitutionName: STANDARD BANK S.A
                InstitutionBranchNumber: 40026
                InstitutionBranchName: KINGSMEAD
            - LinkedFundSource:
                Identifier: 5196341
                Number: 50045199
                Type: Current Account
                Name: Mr DS COOPER
                InstitutionName: STANDARD BANK S.A
                InstitutionBranchNumber: 51001
                InstitutionBranchName: STANDARD BANK SOUTH AFRICA
        204:
          description: No Content
      deprecated: false
  /fundsourcedescriptions:
    get:
      tags: []
      summary: ""
      description: Gets the permissible fund source descriptions
      x-swagger-router-controller: scp_ngi
      operationId: fundSourceDescriptions
      parameters:
      - description: ""
        name: Authorization
        type: string
        required: true
        in: header
      responses:
        200:
          description: OK
          schema:
            title: FundSourceDescriptions
            type: array
            items:
              type: string
        204:
          description: No Content
      deprecated: false
  /permissibletransaction:
    post:
      tags: []
      summary: Checks if the client is allowed to submit transactions
      description: ""
      x-swagger-router-controller: scp_ngi_permissibletransaction
      parameters:
      - schema:
          $ref: '#/definitions/InvestmentTransaction'
        description: ""
        name: body
        in: body
      - description: ""
        name: Authorization
        required: true
        type: string
        in: header
      responses:
        200:
          description: OK
          schema:
            title: permissibletransaction
            type: object
        400:
          description: Bad request
          schema:
            title: Rejection reasons
            type: string
      deprecated: false
  /transaction:
    post:
      tags: []
      summary: Validates or actions a submitted transaction
      description: ""
      x-swagger-router-controller: scp_ngi_transaction
      parameters:
      - schema:
          $ref: '#/definitions/InvestmentTransaction'
        description: ""
        name: body
        in: body
      - description: ""
        name: Authorization
        required: true
        type: string
        in: header
      responses:
        200:
          description: OK
          schema:
            title: permissibletransaction
            type: object
        400:
          description: Bad Request
          schema:
            title: Rejection reasons
            type: string
      deprecated: false
definitions:
  LinkedFundSource:
    properties:
      identifier:
        type: string
        description: The unique system identifier
      number:
        type: string
        description: The record number
      type:
        type: string
        description: The type description
      name:
        type: string
        description: The Friendly name
      institutionName:
        type: string
        description: The institution
      institutionBranchNumber:
        type: string
        description: The branch number
      institutionBranchName:
        type: string
        description: The branch name
  InvestmentTransaction:
    properties:
      acceptedTermsAndConditions:
        type: boolean
        description: An indicator if the terms and conditions have been accepted
      action:
        type: string
        enum:
        - ADD
        - WD
        description: An indication what type of transaction this is
      investorNumber:
        type: string
        description: The investor number
      clientAccountNumber:
        type: string
        description: The investment account to be invested in
      sourceAccountId:
        type: string
        description: The fund source account id
      fundSourceDescription:
        type: string
        description: A description of the fund source
      amount:
        type: string
        description: The amount to be invested
      validate:
        type: boolean
        description: If true the transaction will be validated and not executed
tags: []
x-ibm-configuration:
  enforced: true
  phase: realized
  testable: true
x-ibm-endpoints:
- endpointUrl: https://api-e.nedsecure.co.za/nedbankext
  description: Base Gateway API Endpoint
  type:
